# Generated by Django 3.2 on 2022-02-09 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codex', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('active_char', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('char_intellect', models.IntegerField(default=1)),
                ('char_charm', models.IntegerField(default=1)),
                ('char_coding', models.IntegerField(default=1)),
                ('char_endurace', models.IntegerField(default=1)),
                ('has_job', models.BooleanField(default=False)),
                ('item_intellect', models.IntegerField(blank=True, null=True)),
                ('item_charm', models.IntegerField(blank=True, null=True)),
                ('item_coding', models.IntegerField(blank=True, null=True)),
                ('item_endurance', models.IntegerField(blank=True, null=True)),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='codex.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
