# Generated by Django 3.2 on 2022-02-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_activecharacter_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecharacter',
            name='money',
            field=models.IntegerField(default=20000),
        ),
    ]
