# Generated by Django 3.2 on 2022-02-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220218_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activecharacter',
            name='item_charm',
        ),
        migrations.RemoveField(
            model_name='activecharacter',
            name='item_coding',
        ),
        migrations.RemoveField(
            model_name='activecharacter',
            name='item_endurance',
        ),
        migrations.RemoveField(
            model_name='activecharacter',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='activecharacter',
            name='item_intellect',
        ),
    ]
