# Generated by Django 3.2 on 2022-02-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220223_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecharacter',
            name='energy',
            field=models.IntegerField(default=100),
        ),
    ]
