# Generated by Django 3.2 on 2022-02-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_activecharacter_energy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activecharacter',
            old_name='char_charm',
            new_name='charm',
        ),
        migrations.RenameField(
            model_name='activecharacter',
            old_name='char_coding',
            new_name='coding',
        ),
        migrations.RenameField(
            model_name='activecharacter',
            old_name='char_endurace',
            new_name='endurance',
        ),
        migrations.RenameField(
            model_name='activecharacter',
            old_name='char_intellect',
            new_name='intellect',
        ),
    ]
