# Generated by Django 3.2 on 2022-02-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_activecharacter_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecharacter',
            name='charm_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activecharacter',
            name='coding_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activecharacter',
            name='endurance_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activecharacter',
            name='energy_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activecharacter',
            name='intellect_penalty',
            field=models.IntegerField(default=0),
        ),
    ]
