# Generated by Django 3.2 on 2022-03-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20220224_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_county',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_postcode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_street_address1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_street_address2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_town_or_city',
        ),
    ]
