# Generated by Django 3.2 on 2022-03-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20220308_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activecharacter',
            name='charm_penalty',
        ),
        migrations.RemoveField(
            model_name='activecharacter',
            name='coding_penalty',
        ),
        migrations.RemoveField(
            model_name='activecharacter',
            name='endurance_penalty',
        ),
        migrations.RemoveField(
            model_name='activecharacter',
            name='intellect_penalty',
        ),
    ]
