# Generated by Django 3.2 on 2022-03-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20220324_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecharacter',
            name='money',
            field=models.IntegerField(default=10000),
        ),
    ]
