# Generated by Django 3.2 on 2022-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('friendly_name', models.CharField(blank=True, max_length=100, null=True)),
                ('intellect', models.IntegerField(default=1)),
                ('coldness', models.IntegerField(default=1)),
                ('coding', models.IntegerField(default=1)),
                ('impress_lvl', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='')),
                ('paid', models.BooleanField(default=False)),
                ('level', models.IntegerField(choices=[(1, 'HR'), (2, 'Software Developer'), (3, 'Senior Software Developer'), (4, 'Boss')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('charm', models.IntegerField(default=0)),
                ('intellect', models.IntegerField(default=0)),
                ('endurance', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
