# Generated by Django 3.2 on 2022-02-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_item_coding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='endurance',
            new_name='energy',
        ),
    ]
