# Generated by Django 3.2 on 2022-02-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0004_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
