# Generated by Django 3.2 on 2022-02-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20220223_1350'),
        ('codex', '0005_auto_20220210_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_item', to='profiles.activecharacter'),
        ),
    ]
