# Generated by Django 3.2 on 2022-02-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0006_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
