# Generated by Django 3.2 on 2022-02-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0007_remove_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
