# Generated by Django 3.2 on 2022-03-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0010_interviewer_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='charm_penalty',
        ),
        migrations.RemoveField(
            model_name='item',
            name='coding_penalty',
        ),
        migrations.RemoveField(
            model_name='item',
            name='endurance_penalty',
        ),
        migrations.RemoveField(
            model_name='item',
            name='intellect_penalty',
        ),
    ]
