# Generated by Django 3.2 on 2022-03-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0011_auto_20220328_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
