# Generated by Django 3.2 on 2022-03-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
