# Generated by Django 3.2 on 2022-03-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0005_auto_20220308_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='grand_total',
        ),
    ]
